#############################redis######################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: default
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis
          imagePullPolicy: IfNotPresent
          ports:
            - name: redis
              containerPort: 6379
          volumeMounts:
            - mountPath: /data
              name: redis
      volumes:
        - name: redis
          hostPath:
            path: /data
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379

---
#############################rabbitmq###################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: default
spec:
  selector:
    matchLabels:
      app: rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq
          imagePullPolicy: IfNotPresent
          ports:
            - name: rabbitmq
              containerPort: 6379
          volumeMounts:
            - mountPath: /data
              name: rabbitmq
      volumes:
        - name: rabbitmq
          hostPath:
            path: /data
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
    - name: rabbitmq
      port: 5672
      targetPort: 5672

---
#############################eureka######################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
  namespace: default
spec:
  selector:
    matchLabels:
      app: eureka
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: 192.168.0.107:5000/docker-registry/eureka:1.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          ports:
            - name: eureka
              containerPort: 8084

---
apiVersion: v1
kind: Service
metadata:
  name: eureka
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: eureka
  ports:
    - name: eureka
      port: 8084
      targetPort: 8084

---
#############################config######################################
apiVersion: v1
kind: Service
metadata:
  name: config-external
  namespace: default
spec:
  type: ExternalName
  externalName: github.com

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config
  namespace: default
spec:
  selector:
    matchLabels:
      app: config
  replicas: 1
  template:
    metadata:
      labels:
        app: config
    spec:
      containers:
        - name: config
          image: 192.168.0.107:5000/docker-registry/config:1.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          ports:
            - name: config
              containerPort: 8084

---
apiVersion: v1
kind: Service
metadata:
  name: config
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: config
  ports:
    - name: config
      port: 8082
      targetPort: 8082

---
#############################oauth2######################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2
  namespace: default
spec:
  selector:
    matchLabels:
      app: oauth2
  replicas: 1
  template:
    metadata:
      labels:
        app: oauth2
    spec:
      containers:
        - name: oauth2
          image: 192.168.0.107:5000/docker-registry/oauth2:1.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          ports:
            - name: oauth2
              containerPort: 8016

---
apiVersion: v1
kind: Service
metadata:
  name: oauth2
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: oauth2
  ports:
    - name: oauth2
      port: 8016
      targetPort: 8016

---
#############################zuul######################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zuul
  namespace: default
spec:
  selector:
    matchLabels:
      app: zuul
  replicas: 1
  template:
    metadata:
      labels:
        app: zuul
    spec:
      containers:
        - name: zuul
          image: 192.168.0.107:5000/docker-registry/zuul:1.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          ports:
            - name: zuul
              containerPort: 8086

---
apiVersion: v1
kind: Service
metadata:
  name: zuul
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: zuul
  ports:
    - name: zuul
      port: 8086
      targetPort: 8086

---
#############################ingress######################################
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /
            backend:
              serviceName: eureka
              servicePort: 8084
