apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-deployment
  namespace: default
spec:
  replicas: 1
  selector:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: eureka
        image: eureka
        imagePullPolicy: IfNotPresent
        ports:
        - name: eureka-http
          containerPort: 8084

---
apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: eureka
  ports:
  - name: eureka-service-http
    port: 8084
    targetPort: 8084

---
apiVersion: v1
kind: Service
metadata:
  name: config-external-service
  namespace: default
spec:
  type: ExternalName
  externalName: github.com

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-deployment
  namespace: default
spec:
  replicas: 1
  selector:
      app: config
  template:
    metadata:
      labels:
        app: config
    spec:
      containers:
      - name: config
        image: config
        imagePullPolicy: IfNotPresent
        ports:
        - name: config-http
          containerPort: 8084

---
apiVersion: v1
kind: Service
metadata:
  name: config-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: config
  ports:
  - name: config-service-http
    port: 8082
    targetPort: 8082
    
    
