#############################redis######################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis
          imagePullPolicy: IfNotPresent
          ports:
            - name: redis-http
              containerPort: 6379
          volumeMounts:
            - mountPath: /data
              name: redis-volume
      volumes:
        - name: redis-volume
          hostPath:
            path: /data
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - name: redis-service-http
      port: 6379
      targetPort: 6379

---
#############################rabbitmq###################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq
          imagePullPolicy: IfNotPresent
          ports:
            - name: rabbitmq-http
              containerPort: 6379
          volumeMounts:
            - mountPath: /data
              name: rabbitmq-volume
      volumes:
        - name: rabbitmq-volume
          hostPath:
            path: /data
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
    - name: rabbitmq-service-http
      port: 5672
      targetPort: 5672

---
#############################eureka######################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: eureka
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: 192.168.0.107:5000/docker-registry/eureka:1.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          ports:
            - name: eureka-http
              containerPort: 8084

---
apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: eureka
  ports:
    - name: eureka-service-http
      port: 8084
      targetPort: 8084

---
#############################config######################################
apiVersion: v1
kind: Service
metadata:
  name: config-external-service
  namespace: default
spec:
  type: ExternalName
  externalName: www.github.com

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: config
  replicas: 1
  template:
    metadata:
      labels:
        app: config
    spec:
      containers:
        - name: config
          image: 192.168.0.107:5000/docker-registry/config:1.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          ports:
            - name: config-http
              containerPort: 8084

---
apiVersion: v1
kind: Service
metadata:
  name: config-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: config
  ports:
    - name: config-service-http
      port: 8082
      targetPort: 8082

---
#############################oauth2######################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: oauth2
  replicas: 1
  template:
    metadata:
      labels:
        app: oauth2
    spec:
      containers:
        - name: oauth2
          image: 192.168.0.107:5000/docker-registry/oauth2:1.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          ports:
            - name: oauth2-http
              containerPort: 8016

---
apiVersion: v1
kind: Service
metadata:
  name: oauth2-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: oauth2
  ports:
    - name: oauth2-service-http
      port: 8016
      targetPort: 8016

---
#############################zuul######################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zuul-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: zuul
  replicas: 1
  template:
    metadata:
      labels:
        app: zuul
    spec:
      containers:
        - name: zuul
          image: 192.168.0.107:5000/docker-registry/zuul:1.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          ports:
            - name: zuul-http
              containerPort: 8086

---
apiVersion: v1
kind: Service
metadata:
  name: zuul-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: zuul
  ports:
    - name: zuul-service-http
      port: 8086
      targetPort: 8086

---
#############################ingress######################################
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations: nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /eureka/
            backend:
              serviceName: eureka-service
              servicePort: 8084
          - path: /config/
            backend:
              serviceName: config-service
              servicePort: 8082
          - path: /zuul/
            backend:
              serviceName: zuul-service
              servicePort: 8086
          - path: /oauth2/
            backend:
              serviceName: oauth2-service
              servicePort: 8016
