apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-deployment
  namespace: default
spec:
  replicas: 1
  selector:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: eureka
        image: eureka
        imagePullPolicy: IfNotPresent
        ports:
        - name: eureka-http
          containerPort: 8084

---

apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: eureka
  ports:
  - name: eureka-service-http
    port: 8084
    targetPort: 8084

