security:
  oauth2:
    client:
      clientId: admin
      clientSecret: password
      userAuthorizationUri: http://oauth2-service:8016/oauth/authorize
      accessTokenUri: http://oauth2-service:8016/oauth/token
      clientAuthenticationScheme: form
    resource:
      userInfoUri: http://oauth2-service:8016/user/info
      preferTokenInfo: false

spring:
  session:
    store-type: redis
