security:
  oauth2:
      client:
        clientId: admin
        clientSecret: password
        userAuthorizationUri: http://oauth2:32080/oauth/authorize
        accessTokenUri: http://oauth2:32080/oauth/token
        clientAuthenticationScheme: form
      resource:
        userInfoUri: http://oauth2:32080/user/info
        preferTokenInfo: false

hystrix.command.default.execution.isolation.strategy: SEMAPHORE

hystrix:
  shareSecurityContext: true

spring:
  session:
    store-type: redis
